config/routes.rb
Auth::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "contact" => "static_pages#contact", :as => "contact"
  get "about" => "static_pages#about", :as => "about"
  root :to => "users#new"
  resources :users
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :file
  has_attached_file :docu, :url => "/assets/users/:id/original/:basename.:extension",
  :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
  validates_attachment :docu, :presence => { :message => "File is required" }
  validates_attachment_size :docu, :less_than => 5.megabytes
  validates_attachment_content_type :docu, :content_type => [ 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' ]
  attr_accessible :email, :password_hash, :password_salt, :docu
  attr_accessible :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :email
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Athlete-Trax"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.haml
.navbar.navbar-fixed-bottom
  .navbar-inner
    %ul
      %li.nav.pull-left
        %b
          %i by Hrishikesh Sardar
      %ul.nav.pull-right
        %li= link_to "About Us", about_path
        %li= link_to "Contact", contact_path

app/views/layouts/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    %ul.nav
      %li
        .brand= link_to "Athlete-Trax", root_path, id:"logo"
      %ul.nav.pull-right
        %li= link_to "Home", root_path
        %li= link_to "Sign up", sign_up_path
        %li= link_to "Sign in", log_in_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Athlete-Trax | #{yield(:title)}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      = render 'layouts/header'
      - if current_user
        Logged in as
        = succeed "," do
          %b= current_user.email
        %a{:href => "#{current_user.docu.url} "}
          %b> submitted form
          \.
        = link_to "Log out", log_out_path, class: "btn btn-mini btn_primary"
      - else
        - flash.each do |name, msg|
          .alert= content_tag :div, msg, :id => "flash_#{name}"
        = yield
        = render 'layouts/footer'

app/views/static_pages/about.html.haml
- provide(:title, 'About Us')
%title'About Us'
%h1{:align => "center"} About Us
.row
	.span4
		%h2 Integrated Scheduling
		%p Collegiate athletic programs across the country face everyday scheduling challenges, both academically and athletically. AthleteTrax provides proprietary tools to increase academic performance

	.span4
		%h2 Instant Communication
		%p Instant and constant communication are vital to the success of a collegiate athletic department. AthleteTrax streamlines this process through an interconnected messaging and notification platform

	.span4
		%h2 Data and Form Management
		%p Use the AthleteTrax database manager to archive and organize compliance forms, video footage, workout information, supplement intake and more to increase athletic performance

app/views/static_pages/contact.html.haml
- provide(:title, 'Contact')

%h1{:align => "center"}Contact
%br Email us at customersupport@athlete-trax.com for more information!

app/views/users/new.html.haml
- provide(:title, 'Home')
%h1
  %div{:align => "center"} Welcome to Athlete-Trax
.center.hero-unit
  %h1 Sign Up
  = form_for @user, :html => { :multipart => true } do |f|
    - if @user.errors.any?
      .alert
        .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message
    %p
      = f.label :email
      = f.text_field :email
    %p
      = f.label :password
      = f.password_field :password
    %p
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    %p
      = f.label :docu, "File"
      = f.file_field :docu
    = f.submit "Sign up", class: "btn btn-medium btn_primary"